### PR TITLE
Allow storage table name customization

### PR DESCRIPTION
**Pull request by FreedomMercenary**
Added parameter support for custom azure table name.
Updated docs showing application name and table name options.

### CODE REVIEW

**Comment by abatishchev** [comment]
Why to use your own regex to validate table name rather than allow it to fail with an exception *within* Azure SDK?

**Comment by FreedomMercenary** [comment]
I did it because I tested what error it threw and it was non-descriptive of
what had actually happened (in this test using a dash in the table name):
"An exception of type 'Microsoft.WindowsAzure.Storage.StorageException'
occurred in Microsoft.WindowsAzure.Storage.dll but was not handled in user
code

Additional information: The remote server returned an error: (400) Bad
Request."

No mention of an invalid table name at all when you provide one.  I simply
pulled the regex from the API rules on MSDN at
https://msdn.microsoft.com/library/azure/dd179338.aspx so it would be more
clear why the failure in that specific case.  The above message would not
be useful to me if I had forgotten that only alphanumeric were allowed.  If
you'd like me to remove the check, I can make that change.

**Comment by abatishchev** [comment]
I don't insist but would handle this error differently and reactively:
```csharp
try
{
	await cloudTable.CreateIfNotExistsAsync();
}
catch (StorageException ex) when (((ex.InnerException as WebException)?.Response as HttpWebResponse)?.StatusCode == HttpStatusCode.BadRequest)
{
    throw new Exception("Bad request");
}
```

P.S.
Please [do not use](http://stackoverflow.com/a/5685943/41956) `ApplicationException`. Either `Exception` or some other, custom type.

**Comment by FreedomMercenary** [comment]
We should probably see what the maintainer says.  I see what you're 
trying to do, but the issue is that bad request can mean many things, 
which can be important and would probably be best to just let get thrown 
by the Storage library.  That is separate from trying to isolate when 
you have a bad configuration parameter, which would be what I'm trying 
to do since it would give a direct message toward the issue.  What you 
have below throws exactly what happens without the try, so I'm not sure 
that adds anything, yet still gives no message that you have a bad 
configuration entry.

I agree with your point about ApplicationException, but given the other 
throws in the function for configuration use it, they probably should be 
all the same, so all would be better as just Exception.

**Comment by abatishchev** [comment]
Sure, let's gather opinions. My point is - Azure can change naming rules tomorrow and you'll have to update the code to allow now-legit name.

**Comment by michaelsync** [comment]
Are you guys going to merge this pull request soon?

**Comment by plebann** [comment]
Still waiting...

**Comment by MisinformedDNA** [comment]
Sorry for the delay. Thanks for the prodding.

**Pull request merged**
